### ISSUE TITLE
about mpv mpris and general scripts 

### ISSUE THREAD

**Issue by xscd** [flathub/io.mpv.Mpv#1]
First thank you for the mpv flatpak. I have an question how we can install scripts to mpv. I tried to put it under .var/app/io.mpv.Mpv/config/scripts and .var/app/io.mpv.Mpv/config/mpv/scripts but I couldn't get https://github.com/hoyon/mpv-mpris work. One more question is do you think mpris support should come out of the box or users should install it?

**Comment by fastrizwaan** [comment]
> First thank you for the mpv flatpak. I have an question how we can install scripts to mpv. I tried to put it under .var/app/io.mpv.Mpv/config/scripts and .var/app/io.mpv.Mpv/config/mpv/scripts but I couldn't get https://github.com/hoyon/mpv-mpris work. One more question is do you think mpris support should come out of the box or users should install it?

Yes, ~/.var/app/io.mpv/Mpv/config/scripts is the directory (if installed as user)

mpris needed dbus support, now enabled, mpris is also added to flatpak. Enjoy.

Don't know why mpv is not loading configuration from ~/.config/mpv/ directory !? Like input.conf and mpv.conf are not read.

**Comment by fastrizwaan** [comment]
mpv-mpris is included, hence closing.

**Comment by xscd** [comment]
Thanks. I got the update and it works fine. Guess why it didn't worked first was that I forgot to enable dbus support.
