### ISSUE TITLE
[flatpak-specific] Fallback cursor used while on Gnome wayland

### ISSUE THREAD

**Issue by Mershl** [flathub/io.mpv.Mpv#106]
Tested on Wayland Gnome 42.4. Tested without any mpv configuration (default).

## Cursor while hovering desktop
![image](https://user-images.githubusercontent.com/520251/198009035-2ff4dd93-8f2f-4121-87c5-095c259e4a2b.png)

## Cursor while hovering mpv rpm (mpv-0.34.1-3.fc36.x86_64)
![image](https://user-images.githubusercontent.com/520251/198009166-1c2149d5-8444-4ebd-a15f-e8b0a1be1ba4.png)

## Cursor while hovering mpv flatpak
![image](https://user-images.githubusercontent.com/520251/198009501-6fb01e79-347f-4acd-ba32-36f262b6f550.png)

**Comment by fastrizwaan** [comment]
Where is your cursor theme installed in ~/.icons or in ~/.local/share/icons?
https://github.com/flatpak/flatpak/issues/709

Please test after running these:
```
flatpak --user override --filesystem=/home/$USER/.icons/:ro io.mpv.Mpv
flatpak --user override --filesystem=/usr/share/icons/:ro   io.mpv.Mpv
```

**Comment by fastrizwaan** [comment]
Actually `host:ro` is already enabled, I could use  another cursor example: https://www.gnome-look.org/p/1215613 by copying the extracted dir to `~/.icons `and settings it with `gnome-tweaks` on fedora 36 silverblue.

**Comment by Mershl** [comment]
Ahh, I kinda forget about my theme. I'm using https://copr.fedorainfracloud.org/coprs/nickavem/adw-gtk3/ on Silverblue 36 which automagically leads flatpak to install and use https://github.com/flathub/org.gtk.Gtk3theme.Adwaita-dark. There's most likely a icon missing in the flathub extension of the theme. I'll look into it.

**Comment by Mershl** [comment]
Uninstalling all themes and setting all defaults still shows the issue.
![image](https://user-images.githubusercontent.com/520251/198099388-111fb865-ed38-4fc1-a78c-61b3bb6755d1.png)

**Comment by fastrizwaan** [comment]
So, it looks like a generic flatpak related issue related to themeing and not specific to mpv. Have you tested with other mpv video players from flathub?
I've tested with celluloid, the ~/.icon _mouse cursor does not work_ (same issue as you've reported) with flatpak Celluloid.
https://flathub.org/apps/details/io.github.celluloid_player.Celluloid

**Comment by TingPing** [comment]
This may be this runtime issue which should be resolved in an update in the near future: https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1484

**Comment by Mershl** [comment]
The issue is no longer reproducible as of today.
