### ISSUE TITLE
New release after change to mpv.desktop

### ISSUE THREAD

**Issue by stan-janssen** [flathub/io.mpv.Mpv#11]
There was a problem with this flatpak on elementaryOS (see https://github.com/elementary/dock/issues/119), for which I created a pull request to the mpv-player repository (see https://github.com/mpv-player/mpv/pull/9111) that fixes this issue.

I'm not sure what the next step is; do we need to create a new release of the flatpak or something?

**Comment by fastrizwaan** [comment]
I prefer official releases of mpv; then again, it is a minor issue, I'll patch the desktop file for the time being for elementary os 6. Let's see.

**Comment by stan-janssen** [comment]
> I prefer official releases of mpv; then again, it is a minor issue, I'll patch the desktop file for the time being for elementary os 6. Let's see.

**Comment by fastrizwaan** [comment]
It's updated at flathub, please check and confirm!
