### ISSUE TITLE
The mpv run input command fails

### ISSUE THREAD

**Issue by stax76** [flathub/io.mpv.Mpv#119]
The run input command fails when mpv is installed with flatpak:

Binding:

`k run code /home/username/.config/mpv/input.conf`

```
BS ~> mpv
Starting subprocess failed: init
```

Another unrelated issue is that users are expected to create symlinks, this kind of obstacle does not exist with command line apps installed with Microsoft Store (MSIX) or winget.

```
ln -s ~/.var/app/io.mpv.Mpv/config/mpv/ ~/.config/mpv
ln -s /var/lib/flatpak/app/io.mpv.Mpv/current/active/export/bin/io.mpv.Mpv ~/bin/mpv
```

https://github.com/mpv-player/mpv/issues/10926

**Comment by fastrizwaan** [comment]
Please read https://docs.flatpak.org/en/latest/basic-concepts.html#sandboxes

**Comment by stax76** [comment]
I've read it, but don't understand what it means in regard to mpv's not working run command.

**Comment by fastrizwaan** [comment]
What's `k run code` command? 
You may copy the input.conf to `~/.var/app/io.mpv.Mpv/config/mpv/` and test it.

**Comment by stax76** [comment]
code is 'Visual Studio Code', which did not start at all. I cannot try it since I already uninstalled it because I need a player. I think it's not possible to run anything because code would start with an unknown command line argument.

**Comment by fastrizwaan** [comment]
If you want to run a command using the flatpak use `flatpak run --command=ls io.mpv.Mpv`  and with arguments (ls -lh) `flatpak run --command=ls io.mpv.Mpv -lh`

**Comment by stax76** [comment]
Open input.conf and add the following at the end of the file:

`a run gedit`

Restart mpv in the terminal, press a in mpv, gedit is supposed to run, instead you get an error in the terminal.

**Comment by fastrizwaan** [comment]
Sandboxes
With Flatpak, each application is built and run in an isolated environment, which is called the ‘sandbox’. Each sandbox contains an application and its runtime. By default, the application can only access the contents of its sandbox. Access to user files, network, graphics sockets, subsystems on the bus and devices have to be explicitly granted. **_Access to other things, such as other processes, is deliberately not possible._**

You want to run commands on the system from a sandboxed app,  it is a security risk.

Hint:  `flatpak-spawn --host run gedit` will run commands on the system (which is discouraged, and perhaps disabled)  which needs `flatpak override --talk-name=org.freedesktop.Flatpak  io.mpv.Mpv`

**Comment by stax76** [comment]
I see, thanks for the support.
