### ISSUE TITLE
Flatpak MPV doesn't detect libaacs and can't play Blu-rays

### ISSUE THREAD

**Issue by cyber-sushi** [flathub/io.mpv.Mpv#127]
When trying to play a Blu-ray using `io.mpv.Mpv bd://[title][device]`, MPV complains that no `libaacs` is detected so it can't start the playback, while native MPV works fine. (`libaacs` is installed ofc)
Is there a way to make Flatpak MPV detect libaacs?
Thank you in advance.

**Comment by fastrizwaan** [comment]
I've added libaacs, please test https://github.com/flathub/io.mpv.Mpv/pull/130#issuecomment-1367039802

**Comment by cyber-sushi** [comment]
It works now! Thank you so much
