### ISSUE TITLE
mpris broken with multiple players

### ISSUE THREAD

**Issue by juligreen** [flathub/io.mpv.Mpv#13]
As soon as more than one mpv instance exists mpris breaks since currently the permission looks like this: `--own-name=org.mpris.MediaPlayer2.mpv`, meaning it is only able to control a single instance

To fix it, the permission should look like this: `--own-name=org.mpris.MediaPlayer2.mpv.*`

I copied this from the brave-browser flatpak: https://github.com/flathub/com.brave.Browser/blob/603a6497c913654d81b6a62f211d1add2553134e/com.brave.Browser.yaml#L25

**Comment by fastrizwaan** [comment]
Please check and update after changing to `--own-name=org.mpris.MediaPlayer2.mpv.*`

**Comment by fastrizwaan** [comment]
Please check and update after changing to `--own-name=org.mpris.MediaPlayer2.mpv.*`

**Comment by juligreen** [comment]
I have changed the permission myself and it works :+1:

**Comment by juligreen** [comment]
Well, this way it works for 2 players, but if I open 3 or more mpv instances no no instance seems to pop up in dbus.

I assume this is an upstream issue.

Normally, when the dbus identifier "mpv" is thaken, the new instance would append it's own process id but I assume the real PID is not available inside bubblewrap so the mpris plugin simply appends "instance2".

Threrefore as soon as 3 or more instances are created this results in a name conflict.
