### ISSUE TITLE
MPV not accesible from Konsole

### ISSUE THREAD

**Issue by zohozer** [flathub/io.mpv.Mpv#134]
I installed the MPV version 0.35.0 using `Discover` app on my Steam Deck and I do tried to launch-i from the `Konsole` app but if I type mpv in `Konsole` nothing happens. Seems that `MPV` can't be launched from terminal.

**Comment by Erick555** [comment]
Canonical way to launch flatpak from CLI is `flatpak run io.mpv.Mpv`. Depending on specific config just `io.mpv.Mpv` may work as well. You may also set shell alias for `flatpak run io.mpv.Mpv` named `mpv`.

**Comment by fastrizwaan** [comment]
just create an alias 
```
echo 'alias mpv="flatpak run io.mpv.Mpv"' >> ~/.bashrc
source ~/.bashrc
mpv ~/Videos/video.mp4
```

**Comment by candrapersada** [comment]
> You may also set shell alias for `flatpak run io.mpv.Mpv` named `mpv`.

but why is there no information about this on flathub or in README.md?

**Comment by Erick555** [comment]
Perhaps it could be added somewhere but creating shell aliases isn't knowledge specific to this app or even flatpak.
