### ISSUE TITLE
Some configs regarding subtitles seem broken

### ISSUE THREAD

**Issue by pflanzenandi** [flathub/io.mpv.Mpv#138]
It appears that `sub-font-size=XX` & `sub-bold=yes` do not work for me any more. 
Anyone else experiencing this?

**Comment by fastrizwaan** [comment]
https://mpv.io/manual/master/#subtitles
```
rizvan@debian:~/.build/WineZGUI-main$ cat ~/.var/app/io.mpv.Mpv/config/mpv/mpv.conf 
save-position-on-quit
sub-scale=0.5
sub-bold=yes
sub-italic=yes
```

**Comment by pflanzenandi** [comment]
`This affects ASS subtitles as well, and may lead to incorrect subtitle rendering. Use with care, or use --sub-font-size instead.`

Thanks for mentioning the basic FAQ, but the problems are still remaining. Anyway, just wanted to let the team know.

**Comment by fastrizwaan** [comment]
It works here:
![mpv subtitles](https://user-images.githubusercontent.com/1161682/218985777-d6563dc2-5b11-495f-8ab6-30afb8da76d8.gif)
