### ISSUE TITLE
Generic Wayland icon used in window titlebar

### ISSUE THREAD

**Issue by deadmeu** [flathub/io.mpv.Mpv#145]
The generic Wayland icon is used in the top left corner of the window title bar:
https://i.imgur.com/shBgKgg.png

Not sure if this is a Flatpak packaging issue or an upstream issue. I would appreciate any info as I have this issue with several programs and I'd like to know the cause before raising upstream bug reports.

**Comment by fastrizwaan** [comment]
I guess it is related to wayland server side decoration, https://discussion.fedoraproject.org/t/inconsistant-titlebar-icons-for-wayland-apps/36810/4
