### ISSUE TITLE
Broken video after libplacebo upgrade

### ISSUE THREAD

**Issue by dgcampea** [flathub/io.mpv.Mpv#148]
Commit https://github.com/flathub/io.mpv.Mpv/commit/4db9d0ce43d078563e47a37c56484834e763c625 breaks video playback.
The video is rendered as solid blue, with audio playing in the background.
Reverting to previous version with:
```sh
sudo flatpak update --commit=98c2098ac8fbf8169eb252f7dba028ff8c3aa361c6eccaba2f175a7eb1001afa io.mpv.Mpv
````
fixes this.

## Logs
```
[vo/gpu/libplacebo] shaderc output:
[vo/gpu/libplacebo] error:input: Unknown SPIR-V version 10600
[vo/gpu/libplacebo] shaderc compile status 'error' (1 errors, 0 warnings)
[vo/gpu/libplacebo] vk_compile_glsl(gpu, tmp, GLSL_SHADER_VERTEX, params->vertex_shader, &vert): VK_ERROR_INITIALIZATION_FAILED (../src/vulkan/gpu_pass.c:509)
[vo/gpu/libplacebo] vertex shader source:
```

**Comment by fastrizwaan** [comment]
reverting, though it works with nvidia + xorg here.
https://github.com/flathub/io.mpv.Mpv/pull/149

**Comment by kevinlekiller** [comment]
Commit: 94e7fdccac7f1dd4ab901fc2500fff648ea09a92f55e0131b853702a3a22b41a
      Parent: 98c2098ac8fbf8169eb252f7dba028ff8c3aa361c6eccaba2f175a7eb1001afa
     Subject: Update libplacebo.git to 5.264.0 (4db9d0ce)

Works for me, AMDGPU + Plasma Wayland

**Comment by dgcampea** [comment]
> ```
>   Commit: 94e7fdccac7f1dd4ab901fc2500fff648ea09a92f55e0131b853702a3a22b41a
>   Parent: 98c2098ac8fbf8169eb252f7dba028ff8c3aa361c6eccaba2f175a7eb1001afa
>  Subject: Update libplacebo.git to 5.264.0 (4db9d0ce)
> ```
> 
> Works for me, AMDGPU + Plasma Wayland

Are you using any shaders?

**Comment by kevinlekiller** [comment]
> Are you using any shaders?

Yeah, nothing extreme however. Here's the [mpv.conf](https://codeberg.org/kevincs/config_files/src/branch/main/mpv/mpv.conf#L141-L162)

**Comment by dgcampea** [comment]
> > Are you using any shaders?
> 
> Yeah, nothing extreme however. Here's the [mpv.conf](https://codeberg.org/kevincs/config_files/src/branch/main/mpv/mpv.conf#L141-L162)

My setup is not dissimilar to yours, can you try adding `gpu-api=vulkan` ?

**Comment by kevinlekiller** [comment]
> My setup is not dissimilar to yours, can you try adding gpu-api=vulkan ?

That causes the issue, purple image with sound playing.

I commented out the shaders and set `deband=no`, but still same error,  I'm guessing that shader code is generated at run time, maybe from here ? https://github.com/mpv-player/mpv/blob/master/video/out/gpu/video_shaders.c

**Comment by fastrizwaan** [comment]
Thanks. 
Could u please make a pull request for that x-checker-data.

I'll update shaderc with libpacebo, in the manifest.

**Comment by kevinlekiller** [comment]
> Could u please make a pull request for that x-checker-data.

Will wait until we sort out the issues with shaderc and submit that after.

**Comment by kevinlekiller** [comment]
I've gotten the most recent version of shaderc to work (and io.mpv.Mpv succesfully builds), only thing I don't like is I manually set the version, since I don't know how to get the build directory as a variable, the libglslang.so file is in the build directory.

If we could do that then we could use a `x-checker-data:` on glslang too.

    - name: libplacebo
      buildsystem: meson
      config-opts:
        - -Dvulkan=enabled
        - -Dshaderc=enabled
      cleanup:
        - /include
        - /lib/pkgconfig
      sources:
        - type: git
          url: https://code.videolan.org/videolan/libplacebo.git
          tag: v5.264.0
          x-checker-data:
            type: git
            tag-pattern: ^v([\d.]+)$
          commit: 8ae0648b459d8215bde7772501d5cba17e28bf53
      modules:
        - name: glslang
          buildsystem: cmake-ninja
          config-opts:
            - -DBUILD_SHARED_LIBS=ON
          sources:
            - type: git
              url: https://github.com/KhronosGroup/glslang.git
              tag: 12.0.0
          cleanup:
            - "*"
        - name: shaderc
          buildsystem: cmake-ninja
          builddir: true
          config-opts:
            - -DSHADERC_SKIP_COPYRIGHT_CHECK=ON
            - -DSHADERC_SKIP_EXAMPLES=ON
            - -DSHADERC_SKIP_TESTS=ON
          cleanup:
            - /bin
            - /include
            - /lib/cmake
            - /lib/pkgconfig
          post-install:
            # copy libSPIRV, as it's only available in Sdk
            - install -D /lib/$(gcc --print-multiarch)/libSPIRV*.so /app/lib
          sources:
            - type: git
              url: https://github.com/google/shaderc.git
              tag: v2023.2
              x-checker-data:
                type: git
                tag-pattern: ^v\d{4}\.\d{1,2}$
              commit: 69aead488f9761c3bf478deda5999549ffec2c28
            - type: shell
              commands:
                - sed -i 's|SPIRV/GlslangToSpv.h|glslang/SPIRV/GlslangToSpv.h|' libshaderc_util/src/compiler.cc
                - sed -i 's|add_subdirectory(third_party)||' CMakeLists.txt
                - sed -i 's|add_custom_target(build-version|set(NOT_USE|' CMakeLists.txt
                - |
                  LIB=/lib/$(gcc --print-multiarch)
                  VER_MATCH="[0-9]+\.[^\. ]+"
                  SHADERC=$(grep -m1 -oP "^v$VER_MATCH" CHANGES)
                  SPIRV=v$(grep -oP "(?<=Version:.)$VER_MATCH" $LIB/pkgconfig/SPIRV-Tools-shared.pc)
                  GLSLANG=v12.0.0
                  cat <<- EOF > glslc/src/build-version.inc
                    "shaderc $SHADERC"
                    "spirv-tools $SPIRV"
                    "glslang $GLSLANG"
                  EOF
                - cat glslc/src/build-version.inc
                - sed -i 's|add_dependencies(glslc_exe build-version)||' glslc/CMakeLists.txt

**Comment by kevinlekiller** [comment]
Ok, I got it, will submit a PR.

**Comment by dgcampea** [comment]
I'm afraid the bug might lie elsewhere as now I'm getting:
```
[vo/gpu/libplacebo] shaderc output:
[vo/gpu/libplacebo] input:38: error: 'limitations' : Non-constant-index-expression
....
````

**Comment by kevinlekiller** [comment]
I've been diagnosing this issue, I've figured out the cause.

Will update in #156
