### ISSUE TITLE
Using waf to build mpv is deprecated, we should use meson.

### ISSUE THREAD

**Issue by kevinlekiller** [flathub/io.mpv.Mpv#161]
According to https://github.com/mpv-player/mpv/commit/3858a8102bdeb40120dc1a426db38d84e8f39afd using waf is deprecated, [0.36.0 might be the last version with waf as a build system](https://github.com/mpv-player/mpv/issues/11475#issuecomment-1476281572).

I've been trying to build using meson with:

    - name: mpv
      buildsystem: meson
      config-opts:
        - -Dlibmpv=true
        - -Dbuild-date=false
        - -Dmanpage-build=disabled
        - -Dalsa=disabled
        - -Dsdl2=enabled
        - -Dlibarchive=enabled
        - -Ddvbin=enabled
        - -Dcdda=enabled
        - -Ddvdnav=enabled
        - -Dshaderc=enabled
        - -Dvulkan=enabled
      cleanup:
        - /include
        - /lib/pkgconfig
      post-install:
        - install -D -m644 io.mpv.Mpv.appdata.xml /app/share/appdata/io.mpv.Mpv.appdata.xml
        # save screenshots at ~/Pictures/mpv
        - echo "screenshot-directory=~/Pictures/mpv" > /app/etc/mpv/mpv.conf
      sources:
        - type: file
          path: io.mpv.Mpv.appdata.xml
        - type: git
          url: https://github.com/mpv-player/mpv.git
          tag: v0.35.1
          commit: 140ec21c89d671d392877a7f3b91d67e7d7b9239
          x-checker-data:
              type: git
              tag-pattern: ^v([\d.]+)$

Only issue is the post-install command doesn't find `io.mpv.Mpv.appdata.xml` so it dies.

`install: cannot stat 'io.mpv.Mpv.appdata.xml': No such file or directory`

**Comment by eli-schwartz** [comment]
Upstream provides one of these since https://github.com/mpv-player/mpv/commit/ca9b00145ceeadad36edeac7f87aa6e721b7959b which is automatically installed to the right location.

**Comment by kevinlekiller** [comment]
Thanks for the info @eli-schwartz

Only issue I can see is the package name is io.mpv.Mpv, I'm guessing that's why this repo includes its own appdata.xml file.

**Comment by eli-schwartz** [comment]
Maybe. It may also be worth discussing with the mpv developers which one is correct / better. Does the name actually matter, other than that the version with capitalization exists on flathub and renaming it would probably break users? Perhaps it would be easy to rename the version that upstream distributes.

**Comment by kevinlekiller** [comment]
@eli-schwartz To me it makes more sense to keep the upstream file (mpv.metainfo.xml) as is, without renaming.

None of the other files in [mpv's etc folder](https://github.com/mpv-player/mpv/tree/master/etc) are being renamed.

But we'll see what @fastrizwaan says.

I'll submit a PR with it commented out and put a note in the PR, then @fastrizwaan or another maintainer can change it to their liking.
