### ISSUE TITLE
~/Pictures/mpv-screenshots:create ignores ~/.config/user-dirs.dirs

### ISSUE THREAD

**Issue by ssokolow** [flathub/io.mpv.Mpv#17]
Currently, the filesystem permissions for the screenshots directory are hard-coded to `~/Pictures/mpv-screenshots:create` but I've changed `XDG_PICTURES_DIR` in `~/.config/user-dirs.dirs`, so it just clutters up my `$HOME` with a folder I don't want without asking me.

Please adjust things so it uses something like `xdg-pictures/mpv-screenshots:create` instead. 

...though, if you use a wrapper script to configure MPV to obey that on first run, please make sure it's also named `mpv`. I launch MPV almost exclusively from the command-line and it currently Just Works™ with my script which generates launchers as follows:

```sh
BIN_DIR=~/.local/bin/flatpak

rm -f "$BIN_DIR"/*
mkdir -p "$BIN_DIR"

for X in $(flatpak list --columns=ref); do
    app_command="$(flatpak info -m "$X" | grep command= | cut -d= -f2)"
    cmd_path="$BIN_DIR"/"$app_command"

    if [ -n "$app_command" ]; then
        printf '#!/bin/sh\nexec flatpak run "%s" "$@"' "$X" >"$cmd_path"
        chmod +x "$cmd_path"
    fi
done
```

**Comment by fastrizwaan** [comment]
Thanks, updated to xdg-pictures!

**Comment by dawidpotocki** [comment]
I'm not sure why it got closed?

You still have configured mpv to use an English name, all you did was change it to xdg-pictures in the permissions. This makes screenshots broken for anyone that doesn't have their system in English.

**Comment by fastrizwaan** [comment]
It's 2 years old resolved issue.
If you want a different directory to save your pictures using mpv flatpak
1. Edit your mpv's `mpv.conf` 
```
/var/lib/flatpak/app/io.mpv.Mpv/x86_64/stable/2a0ac46cc09d8447a30ddc53ccaa76fc2f66847d2e234314ae2bc498ec19ef6f/files/etc/mpv/mpv.conf
```
change the directory name in your beloved language
```
screenshot-directory=~/Pictures/mpv
```

2. Add your `screenshot-directory` path using `flatseal` app give write permission.

If you have a better solution which can handle all languages and directories, please go ahead and create a pull request.

Ciao!

**Comment by Erick555** [comment]
wouldn't setting:
echo "screenshot-directory=$XDG_PICTURES_DIR/mpv" > /app/etc/mpv/mpv.conf

just work for everyone?

**Comment by Erick555** [comment]
I guess the OP never used screenshots functionality and just complained about empty directory that was created.

For everyone who does use screenshots and changes their `XDG_PICTURES_DIR` the [fix](https://github.com/flathub/io.mpv.Mpv/commit/02d083ed05ee7868effc08afd7295cf7b2eefad2) for this issue makes only things worse: screenshots are created in path which is read-only (host:ro).

If mpv flatpak hardcodes `~/Pictures` for screenshots path then it should hardcode permission for it as well (thus reverting the fix).

Alternatively it can drop setting screenshots path and leave it for users to handle.

**Comment by ssokolow** [comment]
> If you have a better solution which can handle all languages and directories, please go ahead and create a pull request.

The standard way to query what `xdg-pictures/mpv-screenshots:create` points to is to run `xdg-user-dir PICTURES` (which will parse it out of `~/.config/user-dirs.dirs`) and then concatenate `/mpv-screenshots` onto it.

However, I have no time to familiarize myself with the Flatpak codebase while you, I'd assume, are already familiar with it. (I'm struggling just to re-establish time to maintain my own hobby projects.)

**Comment by Erick555** [comment]
The problem is currently mpv flatpak [sets the path at build time](https://github.com/flathub/io.mpv.Mpv/blob/master/io.mpv.Mpv.yml#L594) so it can't query anything at this point.

**Comment by ssokolow** [comment]
So that's a bug in the Flatpak then, because it will be hard-coding the wrong location on any system that doesn't use an English locale with the default `XDG_PICTURES_DIR` value.

**Comment by Erick555** [comment]
Flatpak doesn't hardcode `~/Pictures` path - mpv does as shown above. This is mpv internal setting that has nothing related to flatpak.
