### ISSUE TITLE
Does the Flatpak version read my user pipewire settings?

### ISSUE THREAD

**Issue by David-Else** [flathub/io.mpv.Mpv#199]
I have created a user config for pipewire in my home directory to set the sample rates that my audio interface provides by doing the following:

 - Create a PipeWire user config file: `cp /usr/share/pipewire/pipewire.conf ~/.config/pipewire/`
 - Add/modify the sound cards available sample rates by editing `~/.config/pipewire/pipewire.conf`:

The Fedora 38 default is:
```
#default.clock.allowed-rates = [ 48000 ]
```
For my audio interface I use:
```
default.clock.allowed-rates = [ 44100 48000 88200 96000 176400 192000 ]
```
My understanding is that unless I do this pipewire will FORCE the audio to be resampled to `48000`, which is of course awful. The default was recently changed to `default.clock.allowed-rates = [ 48000 ]` and was controversial.

So, is MPV respecting my settings, and how could I tell? When it is playing from the terminal it says:
```
AO: [pipewire] 44100Hz stereo 2ch floatp
```
but is this just the source sample rate, how can I tell?

Thanks!

**Comment by David-Else** [comment]
Thanks for the help. I run `pw-dump |grep default.clock.rate` in the sandbox and get:

```
        "default.clock.rate": 48000,
        "default.clock.rate": 48000,
        "default.clock.rate": 48000,
        "default.clock.rate": 48000,
        "default.clock.rate": 48000,
        "default.clock.rate": 48000,
        "default.clock.rate": 48000,
        "default.clock.rate": 48000,
        "default.clock.rate": 48000,
        "default.clock.rate": 48000,
        "default.clock.rate": 48000,
```
But this is not the information I am after. 

If I run `pw-dump | grep default.clock.allowed-rates` in the sandbox I get no result, but if I run it in my normal user terminal I get:

```
"default.clock.allowed-rates": "[ 44100 48000 88200 96000 176400 192000 ]",
```
As expected.

I assume this means that everything is getting resampled to 48000 inside io.mpv.Mpv , or maybe I am mistaken? Cheers!

**Comment by fastrizwaan** [comment]
``
 sudo find /var/ -iname "*pipe*conf"
```

Perhaps you need to edit the pipewire.conf in the /var freedesktop.Platform
```
[rizvan@localhost ~]$ cat /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/22.08/4ba47479a973c9a243112c43f8f58244af34457611e2a26bba8595d08a2b31d7/files/share/pipewire/pipewire.conf|grep rate
    #default.clock.rate          = 48000
    #default.clock.allowed-rates = [ 48000 ]
    #default.video.rate.num      = 25
    #default.video.rate.denom    = 1
    #settings.check-rate         = false
    #        audio.rate             = 48000
```

**Comment by David-Else** [comment]
I manually changed the file as you said, so I get the correct settings in the `org.freedesktop.Platform` file :
```sh
$ cat /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/22.08/4ba47479a973c9a243112c43f8f58244af34457611e2a26bba8595d08a2b31d7/files/share/pipewire/pipewire.c
onf|grep default.clock.allowed-rates
    default.clock.allowed-rates = [ 44100 48000 88200 96000 176400 192000 ]
```
but when I enter the sandbox:

```sh
flatpak run --command=bash io.mpv.Mpv
pw-dump | grep default.clock.allowed-rates
```
I get nothing again :( Could it be using another pipewire config?

```sh
sudo find /var/ -iname "*pipe*conf"

/var/lib/flatpak/app/com.obsproject.Studio/x86_64/stable/2e0857f3aa492750809e87992ac1c986c89f7f7486d7e600fabcffe32ff002a4/files/share/pipewire/pipewire.conf
/var/lib/flatpak/app/com.obsproject.Studio/x86_64/stable/2e0857f3aa492750809e87992ac1c986c89f7f7486d7e600fabcffe32ff002a4/files/share/pipewire/pipewire-pulse.conf
/var/lib/flatpak/app/com.obsproject.Studio/x86_64/stable/2e0857f3aa492750809e87992ac1c986c89f7f7486d7e600fabcffe32ff002a4/files/share/pipewire/pipewire-avb.conf
/var/lib/flatpak/app/com.obsproject.Studio/x86_64/stable/2e0857f3aa492750809e87992ac1c986c89f7f7486d7e600fabcffe32ff002a4/files/share/alsa/alsa.conf.d/50-pipewire.conf
/var/lib/flatpak/app/com.obsproject.Studio/x86_64/stable/2e0857f3aa492750809e87992ac1c986c89f7f7486d7e600fabcffe32ff002a4/files/share/alsa/alsa.conf.d/99-pipewire-default.conf
/var/lib/flatpak/runtime/org.gnome.Platform/x86_64/43/e730a6237e9bb1ac59805e5c734fc5156229fbcb107213272826ea755d98ae40/files/share/pipewire/pipewire.conf
/var/lib/flatpak/runtime/org.gnome.Platform/x86_64/43/e730a6237e9bb1ac59805e5c734fc5156229fbcb107213272826ea755d98ae40/files/share/pipewire/pipewire-aes67.conf
/var/lib/flatpak/runtime/org.gnome.Platform/x86_64/43/e730a6237e9bb1ac59805e5c734fc5156229fbcb107213272826ea755d98ae40/files/share/pipewire/pipewire-pulse.conf
/var/lib/flatpak/runtime/org.gnome.Platform/x86_64/43/e730a6237e9bb1ac59805e5c734fc5156229fbcb107213272826ea755d98ae40/files/share/pipewire/pipewire-avb.conf
/var/lib/flatpak/runtime/org.gnome.Platform/x86_64/42/982438648e909ca4648ef41959440312b25bc1392bec2a7629d6b69824cf535e/files/share/pipewire/pipewire.conf
/var/lib/flatpak/runtime/org.gnome.Platform/x86_64/42/982438648e909ca4648ef41959440312b25bc1392bec2a7629d6b69824cf535e/files/share/pipewire/pipewire-pulse.conf
/var/lib/flatpak/runtime/org.gnome.Platform/x86_64/44/3c158bcbcb8af8163373817cbabeac27a78a2e8876bcf9204209062b5f96daba/files/share/pipewire/pipewire.conf
/var/lib/flatpak/runtime/org.gnome.Platform/x86_64/44/3c158bcbcb8af8163373817cbabeac27a78a2e8876bcf9204209062b5f96daba/files/share/pipewire/pipewire-aes67.conf
/var/lib/flatpak/runtime/org.gnome.Platform/x86_64/44/3c158bcbcb8af8163373817cbabeac27a78a2e8876bcf9204209062b5f96daba/files/share/pipewire/pipewire-pulse.conf
/var/lib/flatpak/runtime/org.gnome.Platform/x86_64/44/3c158bcbcb8af8163373817cbabeac27a78a2e8876bcf9204209062b5f96daba/files/share/pipewire/pipewire-avb.conf
/var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/22.08/4ba47479a973c9a243112c43f8f58244af34457611e2a26bba8595d08a2b31d7/files/share/pipewire/pipewire.conf
/var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/22.08/4ba47479a973c9a243112c43f8f58244af34457611e2a26bba8595d08a2b31d7/files/share/pipewire/pipewire-aes67.conf
/var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/22.08/4ba47479a973c9a243112c43f8f58244af34457611e2a26bba8595d08a2b31d7/files/share/pipewire/pipewire-pulse.conf
/var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/22.08/4ba47479a973c9a243112c43f8f58244af34457611e2a26bba8595d08a2b31d7/files/share/pipewire/pipewire-avb.conf
/var/lib/flatpak/runtime/org.kde.Platform/x86_64/6.4/eebc6ae9242bc7b15f68642d46d307f69f8beeeed08e8ce2671edde5cac3343b/files/share/pipewire/pipewire.conf
/var/lib/flatpak/runtime/org.kde.Platform/x86_64/6.4/eebc6ae9242bc7b15f68642d46d307f69f8beeeed08e8ce2671edde5cac3343b/files/share/pipewire/pipewire-aes67.conf
/var/lib/flatpak/runtime/org.kde.Platform/x86_64/6.4/eebc6ae9242bc7b15f68642d46d307f69f8beeeed08e8ce2671edde5cac3343b/files/share/pipewire/pipewire-pulse.conf
/var/lib/flatpak/runtime/org.kde.Platform/x86_64/6.4/eebc6ae9242bc7b15f68642d46d307f69f8beeeed08e8ce2671edde5cac3343b/files/share/pipewire/pipewire-avb.conf
```

Can io.mpv.Mpv be fixed to read the user config at `~/.config/pipewire/pipewire.conf`? I think that is the correct solution. Even if changing the runtime manually works then the change will be overwritten every time `org.freedesktop.Platform/x86_64/22.08` is updated.

Thanks for looking into this :)

**Comment by Erick555** [comment]
flatpaks are connecting to pipewire daemon from host so the host so whatever pipewire does on your host it;s shared with flatpak apps.

**Comment by fastrizwaan** [comment]
> ```
> Error: Can't remove org.freedesktop.Platform/x86_64/22.08, it is needed for: io.mpv.Mpv, org.kde.krita, org.signal.Signal
> error: Failed to uninstall org.freedesktop.Platform: Can't remove org.freedesktop.Platform/x86_64/22.08, it is needed for: io.mpv.Mpv, org.kde.krita, org.signal.Signal
> ```

you may copy `pipewire.conf` from other freedesktop based runtimes like `/var/lib/flatpak/runtime/org.gnome.Platform/x86_64/43/e730a6237e9bb1ac59805e5c734fc5156229fbcb107213272826ea755d98ae40/files/share/pipewire/pipewire.conf`

if you really want to remove, remove and reinstall 
```
flatpak remove org.freedesktop.Platform/x86_64/22.08 mpv krita signal
flatpak install mpv krita signal
```

your existing settings and data will be not deleted for your apps "mpv, krita, signal" on removing and reinstalling.

**Comment by David-Else** [comment]
Thanks! It seems to work now. Great work on this flatpak, RHEL 9.2 just removed x264 and x265 from MESA so this flatpak is a life saver to get GPU back working again, much needed for 4k :)
