### ISSUE TITLE
no information chmod aftar creating an executable shell script called mpv

### ISSUE THREAD

**Issue by candrapersada** [flathub/io.mpv.Mpv#206]
why is there no information about chmod in `README.md`
for example `chmod a+rx mpv`
> Another method is creating an executable shell script called mpv inside of your path with the following:
> 
>     #!/bin/sh
>     flatpak run io.mpv.Mpv "$@"

aftar create script called mpv. `bash mpv permission denied`

**Comment by fastrizwaan** [comment]
OK. Added. Thanks.
