### ISSUE TITLE
single instance mode

### ISSUE THREAD

**Issue by candrapersada** [flathub/io.mpv.Mpv#215]
how to use single instance mode in mpv flatpak?

**Comment by fastrizwaan** [comment]
it is not supported based on this: https://github.com/mpv-player/mpv/issues/43

You could kill the current instance and start a new one, create a script like `mpv.sh`

```bash
echo '#!/bin/bash
flatpak kill io.mpv.Mpv
flatpak run io.mpv.Mpv "$1"' > mpv.sh
```
as flatpak is only packaging mpv, we can't do much about it.
