### ISSUE TITLE
ALSA support

### ISSUE THREAD

**Issue by waruiji** [flathub/io.mpv.Mpv#221]
Could you please consider enabling ALSA support, as it's currently disabled at https://github.com/flathub/io.mpv.Mpv/blob/64530bc9923ca78fdc8df9b5c1a7135e1d51c7b8/io.mpv.Mpv.yml#L583.

Without ALSA getting pass-through to work is often problematic.
Thanks.

**Comment by fastrizwaan** [comment]
https://github.com/flathub/io.mpv.Mpv/pull/222

removed  `- -Dalsa=disabled`
