### ISSUE TITLE
FFMPEG don't support networking. Failing to play over smb.

### ISSUE THREAD

**Issue by OlegAckbar** [flathub/io.mpv.Mpv#247]
```
$ flatpak run io.mpv.Mpv smb://oleg-laptop.local/Home/Видео/qwe.webm
[ffmpeg] Protocol not found. Make sure ffmpeg/Libav is compiled with networking support.
Failed to open smb://oleg-laptop.local/Home/Видео/qwe.webm.

Exiting... (Errors when loading file)

```

**Comment by fastrizwaan** [comment]
flatpak mpv is meant for GUI and not CLI

when ffmpeg platform supports it https://github.com/flathub/org.freedesktop.Platform.ffmpeg/issues/6 then we can include it in mpv.

perhaps samba package needs to be added to flatpak manifest.

As MPV can be run from nautilus or dolphin file manager which supports samba protocol.

Till then, you could simply use your system's ffmpeg which has samba support.

If you could compile ffmpeg with smb in mpv flatpak, then please open a pull request. 

tried to include --enable-libsmbclient build but fails: https://github.com/flathub/io.mpv.Mpv/pull/248
perhaps samba package needs to be added to flatpak manifest.
