### ISSUE TITLE
Is it possible to avoid empty ~/Videos/mpv-cut?

### ISSUE THREAD

**Issue by Mershl** [flathub/io.mpv.Mpv#25]
Hi @fastrizwaan,

Thanks for maintaining this flatpak. I have a small question regarding the introducion of the video-cutter plugin.

After the video-cutter introduction `io.mpv.Mpv` started creating the folder ~/Videos/mpv-cut on start-up. Is it possible to delay the creation of this folder until usage of the plugin? I use Mpv as a pure media player and the empty mpv-cut folder in Videos is a little inconvenient.

**Comment by Erick555** [comment]
I think it shuld be possible to remove [--filesystem=xdg-videos/mpv-cut:create](https://github.com/flathub/io.mpv.Mpv/blob/master/io.mpv.Mpv.yml#L18) then [add](https://github.com/flathub/io.mpv.Mpv/blob/master/lua-scripts/mpv-video-cutter-script#L10):
```
source ~/.var/app/io.mpv.Mpv/config/user-dirs.dirs
mkdir -p "$XDG_VIDEOS_DIR/mpv-cut"
```

**Comment by Mershl** [comment]
Just noticed that there's another sneaky empty folder `~/Pictures/mpv-screenshots`.

**Comment by fastrizwaan** [comment]
Sure, I'll set Pictures for screenshot and Videos for cut videos.

**Comment by fastrizwaan** [comment]
Please test 
https://flathub.org/builds/#/builders/32/builds/67258

**Comment by Mershl** [comment]
> Create directory on 1st use only.
Screenshot ~/Pictures/mpv
Videocutter ~/Videos/mpv

Tested for screenshots with `Shift+S`: Works beautifully on latest test version.

While testing I noticed that no scripts are installed to .../config/mpv/scripts for a fresh installation. The default shortcuts for `mpv-video-cutter` do not seem to work. Tested with its default shortcut `c`.
```
flatpak remove mpv --delete-data   // --delete-data, equivalent to rm -rf ~/.var/app/io.mpv.Mpv
flatpak install https://dl.flathub.org/build-repo/65085/io.mpv.Mpv.flatpakref
ls -l ~/.var/app/io.mpv.Mpv/config/mpv/scripts
<empty>
```

**Comment by Erick555** [comment]
Note that hardcoding english dir filenames won't play nicely for non-english users (they won't have Videos or Pictures folders) which is why consulting `user-dirs.dirs` is better.

**Comment by fastrizwaan** [comment]
> > Create directory on 1st use only.
> > Screenshot ~/Pictures/mpv
> > Videocutter ~/Videos/mpv
> 
> Tested for screenshots with `s`: Works beautifully on latest test version.
> 
> While testing I noticed that the `c` shortcut for `mpv-video-cutter` does not seem to work for a fresh installation.
> 
> ```
> $ flatpak remove mpv --delete-data   // --delete-data, equivalent to rm -rf ~/.var/app/io.mpv.Mpv
> $ flatpak install https://dl.flathub.org/build-repo/65085/io.mpv.Mpv.flatpakref
> 
> $ flatpak run io.mpv.Mpv <some_video>
>  (+) Video --vid=1 (*) (h264 614x720 30.000fps)
>  (+) Audio --aid=1 (*) (aac 2ch 48000Hz)
> AO: [pulse] 48000Hz stereo 2ch float
> VO: [gpu] 614x720 => 614x720 yuv420p
> AV: 00:00:01 / 00:00:23 (7%) A-V:  0.000
> <pressing c>
> [input] No key binding found for key 'c'.
> ```

Please reinstall mpv-video-cutter-script
```
flatpak run --command=mpv-video-cutter-script io.mpv.Mpv uninstall
flatpak run --command=mpv-video-cutter-script io.mpv.Mpv install
```

**Comment by fastrizwaan** [comment]
> Note that hardcoding english dir filenames won't play nicely for non-english users (they won't have Videos or Pictures folders) which is why consulting `user-dirs.dirs` is better.

Erick, could you please make a pull request. I'd appreciate.

**Comment by fastrizwaan** [comment]
I've removed the bundled scripts. 

Video cutter can be installed from 
https://github.com/fastrizwaan/mpv-video-cutter-linux#for-flatpak-users-of-iompvmpv-at-flathub

**Comment by Mershl** [comment]
Thank you for the fix @fastrizwaan! Works nicely.
