### ISSUE TITLE
URL drag and drop not working

### ISSUE THREAD

**Issue by tazihad** [flathub/io.mpv.Mpv#250]
Dragging a url does nothing. Drag and drop url video playback not working.

Fedora Kinoite 38
wayland.

**Comment by fastrizwaan** [comment]
AFAIK wayland does not support DnD yet.

It does not work with krita and other apps which uses wayland.
https://www.reddit.com/r/kde/comments/p9do2m/drag_and_drop_with_flatpak_in_wayland/?rdt=54643

Perhaps, next update to freedesktop 23.08 will support that DnD.

**Comment by Guldoman** [comment]
DnD woks for me on Arch, GNOME 44.4 Wayland.
Both dragging from a file manager and from a browser.

**Comment by fastrizwaan** [comment]
Yes, my bad, it works in RHEL 9 on wayland too. Perhaps it is related to kionite (silverblue) ostree based issue.

**Comment by tazihad** [comment]
I think it's a mpv, wayland issue. So, I will close this issue.
