### ISSUE TITLE
Split scripts and non-core mpv functionality into flatpak extensions

### ISSUE THREAD

**Issue by dgcampea** [flathub/io.mpv.Mpv#26]
Bundling non-upstream extensions blurs what is part of mpv and what isn't and slightly bloats the package size.
There's also documentation issues and extension bugs that the users may run into, leading them to think its an upstream problem.

io.mpv.Mpv should be only about mpv and its dependencies.
Extra functionality should be introduced via flatpak extension points.

**Comment by fastrizwaan** [comment]
sure
