### ISSUE TITLE
How to remove (or disable) subliminal?

### ISSUE THREAD

**Issue by 07416** [flathub/io.mpv.Mpv#266]
https://flathub.org/apps/io.mpv.Mpv

> subliminal is added for autosub.lua like scripts

I don't have any need for subtitle-downloading integration, and to my knowledge the major providers (which likely operate in the legally grey area) now require additional configuration, possibly even charging for the service. I want to remove subliminal for lower overhead, less attack surface, reduced likelihood of bugs and compatibility issues.

[subliminal](https://github.com/Diaoul/subliminal/) itself doesn't appear to be in active development.

**Comment by fastrizwaan** [comment]
Removed subliminal and dependencies.  https://github.com/flathub/io.mpv.Mpv/pull/270

**Comment by 07416** [comment]
merged, considering as solved
