### ISSUE TITLE
Use upstream changelog

### ISSUE THREAD

**Issue by Victor239** [flathub/io.mpv.Mpv#273]
I see mpv uses a static changelog - could it be switched to using the upstream changelog instead like other Flatpaks? There could also be a link to the Flatpak repo CL but in truth the minor dependency updates and related changes of the Flatpak itself aren't relevant except to contributors, whereas the changes in upstream are usually user-facing like bug fixes and feature changes.

**Comment by fastrizwaan** [comment]
already mentioned flatpak appdata 
https://github.com/fastrizwaan/mpv_extensions/blob/main/io.mpv.Mpv/io.mpv.Mpv.appdata.xml#L36C1-L36C1

**Comment by Victor239** [comment]
Yes, that's what I mean by "static changelog" - it's not actually a changelog, every version just has the same text. 

Instead could you make it so that every new version uses the upstream changelog instead of the same two links each time?

**Comment by fastrizwaan** [comment]
The changelog of flatpak shows the changes of the flatpak. Whereas MPV changelog shows, what's new there. 
How can we integrate these? Do you have any suggestions? I don't want to manually copy paste every time mpv's changelog for flatpak updates. as the changelog of mpv is very big please see: https://github.com/mpv-player/mpv/releases.

**Comment by fastrizwaan** [comment]
I do understand that changelog of neither mpv flatpak nor mpv is given, which feels empty, but the Mpv changelog https://github.com/mpv-player/mpv/releases/tag/v0.36.0 is huge,  and not that useful for general users. Also the appdata.xml file is very finicky about indentation and add that much change info, will be too much effort. I don't want to manually do that. Those who do want to know about the changes can visit the url.

Another issue is that India has banned VLC website, so I may not
