### ISSUE TITLE
Which scripts ship with the mpv Flatpak package?

### ISSUE THREAD

**Issue by 07416** [flathub/io.mpv.Mpv#277]
[Since a subtitle-downloading script (legally a grey area) used to be bundled](https://github.com/flathub/io.mpv.Mpv/issues/266), I'm wondering if there are more perhaps not mentioned in [the Flathub description](https://flathub.org/apps/details/io.mpv.Mpv).

[mpv-mpris](https://github.com/hoyon/mpv-mpris) is referenced: 

> mpv-mpris support - multimedia keys play/pause support

[Guldoman/mpv_inhibit_gnome](https://github.com/Guldoman/mpv_inhibit_gnome#flatpak-support) is not; from the Github readme:

> This plugin has been integrated into the [Flatpak release of mpv](https://flathub.org/apps/details/io.mpv.Mpv)

---

Users should also be able to remove any scripts and addons they may not need, but that's a topic for another issue.

**Comment by Erick555** [comment]
Only those two you mention are shipped. Perhaps appdata should be [adsjusted](https://github.com/flathub/io.mpv.Mpv/blob/master/io.mpv.Mpv.appdata.xml#L28).

**Comment by fastrizwaan** [comment]
> Users should also be able to remove any scripts and addons they may not need, but that's a topic for another issue.

I tried creating mpv extensions, to make it nicer, but there's no good flatpak documentation and no one helped.
https://github.com/fastrizwaan/mpv_extensions
https://www.reddit.com/r/flatpak/comments/wwb9j1/flatpak_extension_testing_locally/

**Comment by fastrizwaan** [comment]
https://github.com/flathub/io.mpv.Mpv/pull/279 updated.
