### ISSUE TITLE
Is the mpv man page installed?

### ISSUE THREAD

**Issue by 07416** [flathub/io.mpv.Mpv#282]
The standard installation of mpv creates the man page on Linux, accessible by running `man mpv`. I greatly miss local documentation after moving to the Flatpak package.

I currently keep loading the webpage `https://mpv.io/manual/stable/` in a browser. I may eventually save and update with a script.

[related](https://askubuntu.com/a/1483096/641895): 

> Flatpaks were primarily developed for graphical user applications. As such, there does not appear to be standard provisions to integrate with the man system, so a flatpak typically will not install a local man page.

**Comment by Erick555** [comment]
It's possible but you would need to execute a long command each time to access it.

**Comment by 07416** [comment]
> It's possible but you would need to execute a long command each time to access it.

It should be possible to at least assign the command to an alias, e.g. `mpv-manual` (Bash aliases can't contain spaces).

**Comment by fastrizwaan** [comment]
This is not specific to mpv flatpak. Other command line flatpak like org.winehq.Wine etc. too do no include man pages. perhaps the man pages are stripped at installation by flatpak-builder. Please raise an issue at https://github.com/flatpak/flatpak and/or https://github.com/flathub

**Comment by Erick555** [comment]
mpv explicitly [disables](https://github.com/flathub/io.mpv.Mpv/blob/master/io.mpv.Mpv.yml#L581) manpages during build.

**Comment by fastrizwaan** [comment]
Thanks, rebuilding without that https://github.com/flathub/io.mpv.Mpv/pull/284

**Comment by fastrizwaan** [comment]
```
flatpak run --command=man io.mpv.Mpv mpv
bwrap: execvp man: No such file or directory

flatpak run --command=man org.gimp.GIMP 
bwrap: execvp man: No such file or directory

flatpak run --command=man org.gnome.TextEditor 
bwrap: execvp man: No such file or directory

```

man command itself is not part of flatpak?

**Comment by Erick555** [comment]
It's only in Sdk so user would need to install 2GB Sdk then running `flatpak run --command=man io.mpv.Mpv mpv`.

In general it's hardly useful.

**Comment by fastrizwaan** [comment]
https://github.com/flathub/io.mpv.Mpv/pull/285 reverting...
