### ISSUE TITLE
Re-include the requests module for python

### ISSUE THREAD

**Issue by azizLIGHT** [flathub/io.mpv.Mpv#291]
The `requests` Python module is used by scripts to do stuff and I noticed it has gone missing in this [commit](https://github.com/flathub/io.mpv.Mpv/commit/269779c5f358676761df848131a72159852b30d8). Please consider adding it back, it is needed by scripts that mpv runs. Thank you

**Comment by fastrizwaan** [comment]
Sure. https://github.com/flathub/io.mpv.Mpv/pull/292
