### ISSUE TITLE
Unable to get "--save-position-on-quit" to work

### ISSUE THREAD

**Issue by v4u6h4n** [flathub/io.mpv.Mpv#295]
Hey everyone, thanks for working on the flatpak version of MPV, love it :-) Everything is pretty smooth, except I haven't had any luck getting the resume playback feature to work. I copied over my configs from the MPV deb I had installed before this, the hotkeys, etc work fine, but not the resume playback.
The following lines are in the an `mpv.conf` in `~/.var/app/io.mpv.Mpv/config/mpv/`

```
# Save playback position when quitting.
--save-position-on-quit

# Only save playback position.
--watch-later-options-clr

# Stops screensaver.
# stop-screensaver = "yes"

--title=MPV Player
```
I added the above directory as allowed in flatseal, which I assumed was the issue, but it had no effect. Any suggestions?

**Comment by Erick555** [comment]
Try starting app as `flatpak run --command=sh --filesystem=host:ro --filesystem=~/.local/state/mpv:create io.mpv.Mpv` and test again.

**Comment by fastrizwaan** [comment]
config file should not use `--`
```
echo "save-position-on-quit"  > /var/home/rizvan/.var/app/io.mpv.Mpv/config/mpv/mpv.conf
```
this should Save playback position when quitting.

**Comment by v4u6h4n** [comment]
Thanks for the suggestions.

> Try starting app (each time) as `flatpak run --filesystem=~/.local/state/mpv:create io.mpv.Mpv` and test again.

I used this, with a video file path appended to the end; the file opens fine, but the playback position doesn't resume when reopened after closing. I can see the following messages:
`Resuming playback. This behavior can be disabled with --no-resume-playback.`
`Saving state.`

> config file should not use `--`
> 
> ```
> echo "save-position-on-quit"  > /var/home/rizvan/.var/app/io.mpv.Mpv/config/mpv/mpv.conf
> ```
> 
> this should Save playback position when quitting.

I removed the `--` from the config file. Howver the suggested command outputs No such file or directory, there doesnt seem to be a `/var/home/rizvan` directory.

Oh, and I'm running Debian stable in case that's relevant.

**Comment by Erick555** [comment]
> I used this, with a video file path appended to the end; the file opens fine, but the playback position doesn't resume when reopened after closing.

Is there anything in `~/.local/state/mpv`?

You may try setting `--watch-later-directory=~/.var/app/io.mpv.Mpv/data/mpv` or similar existing path.

**Comment by Erick555** [comment]
Ok, so the functionality works in flatpak o-o-t-b your config file is wrong (I assumed it was working before).

you need to remove all the `--` sings and also  remove `watch-later-options-clr` completely - this options clears everything from saved sate files which is nonsense.

**Comment by fastrizwaan** [comment]
> Thanks for the suggestions.
> 
> > Try starting app (each time) as `flatpak run --filesystem=~/.local/state/mpv:create io.mpv.Mpv` and test again.
> 
> I used this, with a video file path appended to the end; the file opens fine, but the playback position doesn't resume when reopened after closing. I can see the following messages: `Resuming playback. This behavior can be disabled with --no-resume-playback.` `Saving state.`
> 
> > config file should not use `--`
> > echo "save-position-on-quit"  > /var/home/rizvan/.var/app/io.mpv.Mpv/config/mpv/mpv.conf
> > this should Save playback position when quitting.
> 
> I removed the `--` from the config file. Howver the suggested command outputs No such file or directory, there doesnt seem to be a `/var/home/rizvan` directory.
> 
> Oh, and I'm running Debian stable in case that's relevant.

Sorry, I did not notice, the path was for my user's home directory, here's the correct one:
```
echo "save-position-on-quit"  > ~/.var/app/io.mpv.Mpv/config/mpv/mpv.conf
```

**Comment by v4u6h4n** [comment]
> Ok, so the functionality works in flatpak o-o-t-b but your config file is wrong (I assumed it was working before).
> 
> you need to remove all the `--` signs and also remove `watch-later-options-clr` completely - this options clears everything from saved sate files which is nonsense.
> 
> This is how your `mpv.conf` should look like:
> 
> ```
> # Save playback position when quitting.
> save-position-on-quit
> 
> # Stops screensaver.
> # stop-screensaver = "yes"
> 
> title=MPV Player
> ```

Okay that did the trick *sigh of relief* Thanks for the help everyone :-)

I'm wondering if either the MPV [documentation](https://mpv.io/manual/stable/) should be updated, or rather if it this is flatpak specific, if there should be some mention that the conf formatting is different in the readme.md?

**Comment by Erick555** [comment]
In the linked documentation under **Putting Command Line Options into the Configuration File** you can see table which shows how commandline options should be translated to config file:

`--flag` -> `flag`
`--opt=val` -> `opt=val`

So this is the same what we discussed above.
