### ISSUE TITLE
Vulkan video decoding support

### ISSUE THREAD

**Issue by waruiji** [flathub/io.mpv.Mpv#306]
Could you please consider enabling Vulkan video decoding support?
If I [understand](https://github.com/mpv-player/mpv/blob/438ead7a3d50468b8150f2dc2727b96c78db9874/meson_options.txt#L104) [correctly](https://github.com/mpv-player/mpv/blob/438ead7a3d50468b8150f2dc2727b96c78db9874/meson.build#L1320-L1322) `-Dvulkan-interop=true` needs to be added to build options.

Thanks!

**Comment by fastrizwaan** [comment]
https://github.com/flathub/io.mpv.Mpv/pull/308

../meson.build:1330:0: ERROR: Feature vulkan-interop cannot be enabled: Vulkan Interop requires vulkan headers >= 1.3.238, libplacebo >= 6.278.0, and libavutil >= 58.11.100

Could you create a PR, India blocks Videolan domain. So can't do much about it.

**Comment by waruiji** [comment]
Will try!

**Comment by waruiji** [comment]
Closing as after the recent updates the Vulkan support seems to be working as expected!
