### ISSUE TITLE
`mpv_inhibit_gnome` is no longer needed as of GNOME 45

### ISSUE THREAD

**Issue by zefr0x** [flathub/io.mpv.Mpv#358]
As mentioned in https://github.com/Guldoman/mpv_inhibit_gnome/issues/10, `mpv_inhibit_gnome` plugin is no longer needed. Also as discussed here https://github.com/flathub/io.mpv.Mpv/pull/346, it should go to extensions since it's not a main functionality by mpv.

**Comment by fastrizwaan** [comment]
Not everyone is using gnome 45, and flatpak supported distros like Redhat 9 will not have gnome 45 for next 8 years. And Could you create a PR for the plugin? I could not find any workable documentation for the plugin. So, I can't do that.

**Comment by fastrizwaan** [comment]
https://github.com/flathub/io.mpv.Mpv/issues/358#issuecomment-1870752286
