### ISSUE TITLE
No sound with pipewire, but sound is present with pulseaudio

### ISSUE THREAD

**Issue by Sunspark-007** [flathub/io.mpv.Mpv#376]
Audio used to be present with the flatpak of 0.36, with 0.37 there is no audio.

--ao=pipewire is silent, but --ao=pulse outputs sound.

https://github.com/mpv-player/mpv/issues/13312

**Comment by fastrizwaan** [comment]
flatpak mpv has updated the runtime to freedesktop 23.08 which has newer pipewire.

**Comment by Erick555** [comment]
mpv uses only one freedesktop version (currently 23.08.x) at time regardless of how many you have installed. Does other apps use also 23.08.x?

BTW: this tooltip on screenshot is completely bogus

**Comment by Sunspark-007** [comment]
Yes, I have 6 flatpaks using 23.08 (including mpv). One of them is Zoom. I fired it up and went into settings and tested audio.. it plays fine on all audio outputs. The stuff using 22.08 freedesktop also works.

Some other flatpaks use a different variant, org.kde.Platform/x86_64/5.15-23.08. One of those is Haruna which uses libmpv. No audio from that one, but vlc also uses the same runtime and does have audio.

**Comment by t-8ch** [comment]
Can you provide an mpv log with ` --msg-level=ao/pipewire=trace`?

Is this the latest steamOS? The pipewire daemon on the host is quite a bit older than the one in the flatpak.

**Comment by t-8ch** [comment]
According to the logs mpv properly forwards the samples to the pipewire daemon when pipewire asks for them.
So I'm not sure what mpv could do differently.

Could you try it with the newer version?

**Comment by Sunspark-007** [comment]
> Could you try it with the newer SteamOS version?

I did, sound works. :(

I also observed the other 2 issues involving seeking freezing and switching to hardware decoding using the keyboard were also not present.

I ran the command to see what version of pipewire it is using. It is using 0.3.62 so only a very small incremental change from 0.3.59.

Something in userspace has been broken between the two versions, but I don't have an understanding of what exactly. I'm thinking that because the KDE desktop remains the same perhaps there are configuration files that have been changed that are now conflicting in terms of settings.

I also ran the pipewire trace command again in 3.5.5 to compare.
[355_pipewire_trace.txt](https://github.com/flathub/io.mpv.Mpv/files/13994950/355_pipewire_trace.txt)

**Comment by t-8ch** [comment]
To be honest if it works with the new version, finding out what is broken on the old one is a very academic exercise.
Nobody will fix this old version and in the end it will be a known issue, as it is already fixed.

Maybe newer versions of 3.5.x are more stable?

**Comment by Sunspark-007** [comment]
As you say, it won't be fixed, but it's just so strange in the specificity of the issue.. why only mpv and libmpv and nothing else?

I just feel that it should affect everything, not merely a single app. I did try clean-uninstalling mpv including the user data and re-installing it, but it did not change anything.

I'd like to test using an older mpv version to see if it is different since it used to be fine. Would you know offhand what command to use to grab the 0.36 version?

**Comment by t-8ch** [comment]
Are you sure that the other applications
* are actually using the native Pipewire protocol (and not pulse/alsa)
* are using the same version of libpipewire
?

Please note that these are all pre 1.0 versions of pipewire, so while the version numbers may be close the actual differences can be fairly large.

I have no real clue on how to use flatpak, sorry.

**Comment by Sunspark-007** [comment]
Well, well, well..

sudo flatpak update --commit=ab5661d5510eea41ba27bf1211d3407009628211547efaa1e64f10fc57780657 io.mpv.Mpv

The above command will downgrade to the very last version of 0.36 right before 0.37 was released.

Guess what?

SOUND WORKS!! Switching to hardware decoding using the keyboard works without freezing. Clicking on seek bar positions works without freezing.

0.37 is buggy.

**Comment by fastrizwaan** [comment]
it's not buggy, the freedesktop verison 23.08 has new version of pipewire than what older version of distros have.

you could also try 0.37 with 22.08 without the freedesktop 23.08 from https://github.com/flathub/io.mpv.Mpv/commit/333a91da7d13d29a5d0a41757e8838b2242ed8cc

```
sudo flatpak update --commit=5b9dfcbbf3cadf320ea4baf4440f4e40803d290eaa6d6e2ff6d0039a5e5ea315 io.mpv.Mpv
```

to get that commit from io.mpv.Mpv flathub git
```
flatpak --system remote-info --log flathub io.mpv.Mpv|grep -A3 -B3 "0\.37"
flatpak --system remote-info --log flathub io.mpv.Mpv|grep -A3 -B3 "333a91d"
```

**Comment by Sunspark-007** [comment]
> it's not buggy, the freedesktop verison 23.08 has new version of pipewire than what older version of distros have.
> 
> you could also try 0.37 with 22.08 without the freedesktop 23.08 from [333a91d](https://github.com/flathub/io.mpv.Mpv/commit/333a91da7d13d29a5d0a41757e8838b2242ed8cc)
> 
> ```
> sudo flatpak update --commit=5b9dfcbbf3cadf320ea4baf4440f4e40803d290eaa6d6e2ff6d0039a5e5ea315 io.mpv.Mpv
> ```

I confirm that this works as well, sound, etc. is present. Thank you.

This situation is interesting to me, packaging is complicated, even in an environment that is advertised as coming with everything that is needed.
