### ISSUE TITLE
How to remove any built-in extensions?

### ISSUE THREAD

**Issue by in-plaintext** [flathub/io.mpv.Mpv#379]
I may want to remove some or all   third-party extensions [the Flatpak build of mpv ships with](https://github.com/flathub/io.mpv.Mpv/issues/277). Can the addon files at least be wiped with a script after every mpv Flatpak update?

I see no LUA files with descriptive titles:

    $ fd --extension lua . /var/lib/flatpak/app/io.mpv.Mpv/

related discussions:
https://github.com/flathub/io.mpv.Mpv/issues/358  
https://github.com/flathub/io.mpv.Mpv/issues/81

**Comment by in-plaintext** [comment]
[this issue was hidden for months due to my Github account being shadowbanned — I'll delete this reply later]

**Comment by fastrizwaan** [comment]
yes, mpv does not depend on it.

> Can the .so files in `/var/lib/flatpak/app/io.mpv.Mpv/x86_64/stable/*/files/etc/mpv/scripts/` be safely removed?
> 
> `mpris.so mpv_inhibit_gnome.so`
> 
> The folder can be found by, for instance, running:
> 
> ```
> fd --glob --type directory 'scripts' /var/lib/flatpak/app/io.mpv.Mpv/
> ```

**Comment by fastrizwaan** [comment]
or  you can build it yourself locally and install without those plugins and other deps.
