### ISSUE TITLE
0.38 player hangs when trying stats [i or shift+i] 

### ISSUE THREAD

**Issue by freewalker-panda** [flathub/io.mpv.Mpv#445]
Good day! 
After 0.38 release player doesn't show stats (script bound to "i" key). It just hangs without possibility to close a window. Could anybody confirm? 
Thanks.

**Comment by fastrizwaan** [comment]
I have video cutter script bound to "i" key (c then c then i  to cut), using shift+i works

https://github.com/fastrizwaan/mpv-video-cutter-linux

```
cd /tmp
git clone https://github.com/fastrizwaan/mpv-video-cutter-linux.git
mkdir -p ~/.var/app/io.mpv.Mpv/config/mpv/scripts/
cp mpv-video-cutter-linux/flatpak/* ~/.var/app/io.mpv.Mpv/config/mpv/scripts/
chmod 0755 ~/.var/app/io.mpv.Mpv/config/mpv/scripts/c_concat.sh
chmod 0755 ~/.var/app/io.mpv.Mpv/config/mpv/scripts/c_concat2.sh
```

**Comment by NineMeowICT** [comment]
Same here.

**Comment by fastrizwaan** [comment]
What can I or mpv devs do about 3rd party scripts which is stealing mpv shortcuts?

**Comment by freewalker-panda** [comment]
> What can I or mpv devs do about 3rd party scripts which is stealing mpv shortcuts?

Do you mean that "flathub version" uses 3dparty scripts? Asking because stats in 0.38 mpv works as usual. Instead flathub 0.38 - still hangs after "i" or "Shift+i" (Linux mint freshly installed, no user scripts at all in both cases).

**Comment by freewalker-panda** [comment]
...but no problem with freshly installed fedora + flatpak mpv 0.38 
It seems like mint problem, so question could be closed. 
Thanks for everyone for this discussion.
