### ISSUE TITLE
Rename to `io.mpv.mpv` ?

### ISSUE THREAD

**Issue by albertescanes** [flathub/io.mpv.Mpv#580]
Maybe it should be considered to rename the application ID to `io.mpv.mpv`, as this is the upstream app ID, rather than `io.mpv.Mpv`.

**Comment by fastrizwaan** [comment]
yes, when I first uploaded the io.mpv.Mpv, i wanted to rename it to io.mpv.mpv, but then I was told it was ok with io.mpv.Mpv. 
https://github.com/mpv-player/mpv/blob/master/etc/mpv.metainfo.xml

@TingPing i don't know the process to rename an existing published app at flathub, will simply changing the id would do?

**Comment by Erick555** [comment]
You would need to EOL this app and republish new one. I don't think it's worth it.

**Comment by nanderer** [comment]
i dont care, i created a mpv wrapper like this to dont use package naming at all

```
#!/bin/bash
flatpak run io.mpv.Mpv "$@"


```
changing it now would brake probably a lot of things...

**Comment by fastrizwaan** [comment]
Sorry, I can't change the name, unless it's causing any issue, or when mpv developers take over this flatpak, they can use the proper name. 

The fedora repo also uses this `io.mpv.Mpv` name (perhaps they copied flathub's mpv manifest):
```
$ flatpak install mpv
Looking for matches…
Remotes found with refs similar to ‘mpv’:

   1) ‘fedora’ (system)
   2) ‘flathub’ (system)
   3) ‘flathub’ (user)

Which do you want to use (0 to abort)? [0-3]: 1
Found ref ‘app/io.mpv.Mpv/x86_64/stable’ in remote ‘fedora’ (system).
Use this ref? [Y/n]:
```
