### ISSUE TITLE
No changelog for mpv flatpak

### ISSUE THREAD

**Issue by pflanzenandi** [flathub/io.mpv.Mpv#64]
in the last 2 weeks the flatpak version has been rebuilt several times. when i search for changes i am directed to the github relase page stand jan. '22.

would it be possible to document a change log?

**Comment by fastrizwaan** [comment]
mpv changelog is for mpv package. Flatpak also updates various dependent libraries like yt-dlp, etc. Hence those can't be a part of mpv changelog. flatpak related changes can be seen here at https://github.com/flathub/io.mpv.Mpv/commits/master

**Comment by pflanzenandi** [comment]
Thx!
