### ISSUE TITLE
Question: access to locally installed app

### ISSUE THREAD

**Issue by arvigeus** [flathub/io.mpv.Mpv#66]
I am trying to add [mpv-autosub](https://github.com/davidde/mpv-autosub) plugin, which requires subliminal. I tried to give `mpv` access to `~/.local/bin` and set `~/.local/bin/subliminal` in the plugin config, but it still does not work. What am I missing?

**Comment by Erick555** [comment]
Flatpak apps are isolated from other apps.

**Comment by fastrizwaan** [comment]
you may test with `flatpak install https://dl.flathub.org/build-repo/88527/io.mpv.Mpv.flatpakref`

**Comment by arvigeus** [comment]
```sh
[arvigeus@fedora ~]$ flatpak run --filesystem=host --command=bash io.mpv.Mpv 
[📦 io.mpv.Mpv ~]$ subliminal -v
Traceback (most recent call last):
  File "/var/home/arvigeus/.local/bin/subliminal", line 5, in <module>
    from subliminal.cli import subliminal
ModuleNotFoundError: No module named 'subliminal'
```

Anyway, I don't think this is the right way to do it (manually writing what I want). Probably I should just make a shell script that automates this. Or use VLC because it has similar functionality.

Thanks for the swift response!

**Comment by fastrizwaan** [comment]
> Anyway, I don't think this is the right way to do it (manually writing what I want). Probably I should just make a shell script that automates this. Or use VLC because it has similar functionality.

I think the autosub.lua script has issue with variable `local subliminal=` it should just use $PATH instead of absolute path, so that wrappers work.

> Thanks for the swift response!
You're welcome!

**Comment by fastrizwaan** [comment]
Reverted subliminal wrapper. Security is important. https://github.com/flathub/io.mpv.Mpv/commit/b8877cafbe82b918e393b83f593f8c9125786b42

**Comment by Erick555** [comment]
One option would be to add subminimal into fatpak although it has significant number of python dependencies.

**Comment by fastrizwaan** [comment]
Included subliminal with commit https://github.com/flathub/io.mpv.Mpv/commit/4d88d8bcc18dbe4bab486f6cf45ae5237b757072

autosub.lua downloads subtitles as expected. 

@arvigeus kindly test. make sure write permission to HOME or HOST for downloading subtitles and 

set `local subliminal = '/app/bin/subliminal'` in `autosub.lua` file.

**Comment by arvigeus** [comment]
Works like a charm! Maybe this should be added as a listed feature in flathub description?

**Comment by fastrizwaan** [comment]
autosub.lua installation notes
```
cd /tmp
git clone https://github.com/davidde/mpv-autosub.git
cd mpv-autosub/
sed "s/local subliminal = .*$/local subliminal = '\/app\/bin\/subliminal/g" -i autosub.lua 
mkdir -p ~/.var/app/io.mpv.Mpv/config/mpv/scripts/
cp autosub.lua ~/.var/app/io.mpv.Mpv/config/mpv/scripts/
flatpak --user override --filesystem=host io.mpv.Mpv ; # to download subtitles in the same directory containing video
```
