### ISSUE TITLE
mpv_inhibit_gnome for gnome idle inhibition

### ISSUE THREAD

**Issue by Deminder** [flathub/io.mpv.Mpv#94]
Due to political reasons, idle inhibition of mpv is not supported on gnome wayland. 
However, there is a cplugin [mpv_inhibit_gnome](https://github.com/Guldoman/mpv_inhibit_gnome) for this.
Wouldn't it be nice to have it bundled in this flatpak?

**Comment by fastrizwaan** [comment]
I'll look into it...

**Comment by fastrizwaan** [comment]
Please check and confirm, whether it works. Thank you!

**Comment by Deminder** [comment]
> To build, the `libdbus-1` library is needed, as well as the header files for `mpv`

@fastrizwaan I think, the build is missing the `dbus` headers. 
```
[mpv_inhibit_gnome] C plugin error: '/app/etc/mpv/scripts/mpv_inhibit_gnome.so: undefined symbol: dbus_bus_get'
[mpv_inhibit_gnome] Could not load SO plugin /app/etc/mpv/scripts/mpv_inhibit_gnome.so
```

**Comment by Erick555** [comment]
I think you need to buold the mpv_inhibit_gnome library from source to keep ABI compatible with runtime.

**Comment by Deminder** [comment]
We need to wait for https://github.com/Guldoman/mpv_inhibit_gnome/pull/5.

**Comment by fastrizwaan** [comment]
> I think you need to build the mpv_inhibit_gnome library from source (it uses `make`) to keep ABI compatible with runtime.

Yes, we make it then copy the .so file to config/scripts dir.
https://github.com/flathub/io.mpv.Mpv/commit/24894eef8e83d0908388555f6ee8eae13611a3cf

**Comment by fastrizwaan** [comment]
> We need to wait for [Guldoman/mpv_inhibit_gnome#5](https://github.com/Guldoman/mpv_inhibit_gnome/pull/5).

Sure, kindly make a pull request after it. Thanks.
